# Generated by Django 5.1.5 on 2025-01-23 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Moto",
        ),
    ]
